ERM-1761 Apply keyboard shortcuts modal guidelines
folio-org/ui-dashboard pull request #93
Opened 2021-07-20 18:22 UTC by CalamityC

* import erm wide default shortcuts from stripes-components
* create app specific keyboard shortcuts file
* add translation keys

2021-07-21 18:06 UTC, aditya-matukumalli requested changes

2021-07-21 18:06 UTC, aditya-matukumalli commented on src/index.js
> +  const commands = appKeyboardShortcuts.concat(ermDefaultKeyboardShortcuts);
Lets use the spread operator here

```suggestion
  const commands =  [...appKeyboardShortcuts, ...ermDefaultKeyboardShortcuts]
```

2021-07-22 14:36 UTC, CalamityC commented
Do not merge before [#399](https://github.com/folio-org/stripes-erm-components/pull/399) has been merged

2021-07-22 15:51 UTC, aditya-matukumalli approved these changes

2021-11-15 15:18 UTC, aditya-matukumalli requested changes

2021-11-15 15:18 UTC, aditya-matukumalli commented on src/index.js
> +      { 'shortcut': 'save', 'label': 'Save form changes' }
All the labels here need to be translatable strings. You can bring intl via `useIntl` hook and translate them

eg: `{ 'shortcut': 'new', 'label': intl.formatMessage({ id: ui-dashboard.createNewWidget )}`

2021-11-15 17:20 UTC, aditya-matukumalli approved these changes

2021-11-15 17:20 UTC, merged